[project]
name = "stock-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "yahoo-fin>=0.8.9.1",
    "yfinance>=0.2.66",
]
